[package]
name = "pallet-beefy"
version = "28.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
repository.workspace = true
description = "BEEFY FRAME pallet"
homepage = "https://substrate.io"

[lints]
workspace = true

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
log = { workspace = true }
scale-info = { version = "2.10.0", default-features = false, features = ["derive", "serde"] }
serde = { optional = true, workspace = true, default-features = true }
frame-support = { path = "../support", default-features = false }
frame-system = { path = "../system", default-features = false }
pallet-authorship = { path = "../authorship", default-features = false }
pallet-session = { path = "../session", default-features = false }
sp-consensus-beefy = { path = "../../primitives/consensus/beefy", default-features = false, features = ["serde"] }
sp-runtime = { path = "../../primitives/runtime", default-features = false, features = ["serde"] }
sp-session = { path = "../../primitives/session", default-features = false }
sp-staking = { path = "../../primitives/staking", default-features = false, features = ["serde"] }
sp-std = { path = "../../primitives/std", default-features = false }

ark-serialize = { version = "0.4.0", default-features = false }
ark-std = { version = "0.4.0", default-features = false }
ark-bls12-377 = { version = "0.4.0", features = ["curve"], default-features = false }
# etf-crypto-primitives = { path = "../../../../etf-sdk/etf-crypto-primitives", default-features = false }
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
frame-election-provider-support = { path = "../election-provider-support" }
pallet-balances = { path = "../balances" }
pallet-offences = { path = "../offences" }
pallet-staking = { path = "../staking" }
pallet-staking-reward-curve = { path = "../staking/reward-curve" }
pallet-timestamp = { path = "../timestamp" }
sp-core = { path = "../../primitives/core" }
sp-io = { path = "../../primitives/io" }
sp-staking = { path = "../../primitives/staking" }
sp-state-machine = { path = "../../primitives/state-machine", default-features = false }

[features]
default = ["std"]
std = [
	"ark-std/std",
	"ark-serialize/std",
	"ark-bls12-377/std",
	# "etf-crypto-primitives/std",
	"codec/std",
	"frame-election-provider-support/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"pallet-offences/std",
	"pallet-session/std",
	"pallet-staking/std",
	"pallet-timestamp/std",
	"scale-info/std",
	"serde/std",
	"sp-consensus-beefy/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"sp-state-machine/std",
	"sp-std/std",
]
try-runtime = [
	"frame-election-provider-support/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-offences/try-runtime",
	"pallet-session/try-runtime",
	"pallet-staking/try-runtime",
	"pallet-timestamp/try-runtime",
	"sp-runtime/try-runtime",
]
